from Programme.classPronom import *
from Programme.classAffichagePerso import *
from Programme.classBouton import *
from Programme.classMusique import *
from Programme.classImage import *
from Programme.fonctionAffichage import *
from Programme.fonctionText import *
from Programme.maison import *
from Programme.choix import *
from Programme.fermer import *
from Scene.AlScene import *
from Programme.enter_son_nom import *
from Scene.JohnScene import *
from Sauvegarde.sauvegarde import *
from Scene.LaboulengereScene import *
from Scene.train import *
from Scene.CapucineScene import *